services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      VERSION: 1.20.2
    deploy:
      resources:
        limits:
          memory: 1.5G
    volumes:
      - "./minecraft:/data"