/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import javax.swing.JPanel;
import postgressql.ConexionSQL;

/**
 *
 * @author oracle
 */
public class EliminarLibros extends javax.swing.JPanel {

    ConexionSQL obxC = new ConexionSQL();
    
    JPanel pMenu;
    
    /**
     * Creates new form EliminarLibros
     */
    public EliminarLibros() {
        initComponents();
    }

    public void recogerPanelMenu(JPanel panel){
        pMenu = panel;
        eError.setVisible(false);
        eBorrado.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bVolver = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lID = new javax.swing.JTextField();
        eError = new javax.swing.JLabel();
        eBorrado = new javax.swing.JLabel();

        bVolver.setText("VOLVER");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        bBorrar.setText("BORRAR");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Pon el ID del libro a borrar");

        eError.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        eError.setForeground(new java.awt.Color(255, 0, 0));
        eError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eError.setText("LIBRO NO ENCONTRADO");

        eBorrado.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        eBorrado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eBorrado.setText("LIBRO BORRADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bVolver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bBorrar)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lID))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eBorrado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eError, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(eError)
                .addGap(18, 18, 18)
                .addComponent(eBorrado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bVolver)
                    .addComponent(bBorrar))
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pMenu.setVisible(true);
    }//GEN-LAST:event_bVolverActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
        // TODO add your handling code here:
        eError.setVisible(false);
        eBorrado.setVisible(false);
        if(lID.getText().equals("")){
            eError.setText("EL ID NO PUEDE SER VACIO");
            eError.setVisible(true);
        }
        else{
            obxC.borrarLibro(Integer.parseInt(lID.getText()), eError, eBorrado);
        }
    }//GEN-LAST:event_bBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBorrar;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel eBorrado;
    private javax.swing.JLabel eError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField lID;
    // End of variables declaration//GEN-END:variables
}
