/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package presentacion;

/**
 *
 * @author dam1
 */
public class PanelCrearEmpleado extends javax.swing.JPanel {

    /**
     * Creates new form panel2
     */
    public PanelCrearEmpleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboEmpleado = new javax.swing.JComboBox<>();
        eEmpleado = new javax.swing.JLabel();
        lNombre = new javax.swing.JTextField();
        eNombre = new javax.swing.JLabel();
        lApellidos = new javax.swing.JTextField();
        eApellidos = new javax.swing.JLabel();
        eCambia = new javax.swing.JLabel();
        lCambia = new javax.swing.JTextField();

        comboEmpleado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contratado", "Destajo" }));
        comboEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEmpleadoActionPerformed(evt);
            }
        });

        eEmpleado.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        eEmpleado.setText("¿Qué tipo de empleado quieres añadir?");

        lNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNombreActionPerformed(evt);
            }
        });

        eNombre.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        eNombre.setText("¿Cuál es su nombre?");

        lApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lApellidosActionPerformed(evt);
            }
        });

        eApellidos.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        eApellidos.setText("¿Cuál son sus apellidos?");

        eCambia.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        eCambia.setText("¿Cuál es su sueldo básico?");

        lCambia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lCambia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lCambiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(344, 344, 344)
                        .addComponent(comboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(eEmpleado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(eNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lCambia, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(227, 227, 227))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eApellidos)
                        .addGap(289, 289, 289))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eCambia)
                        .addGap(277, 277, 277))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(eEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(eNombre)
                .addGap(18, 18, 18)
                .addComponent(lNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(eApellidos)
                .addGap(18, 18, 18)
                .addComponent(lApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(eCambia)
                .addGap(18, 18, 18)
                .addComponent(lCambia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void comboEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEmpleadoActionPerformed
        if(comboEmpleado.getSelectedIndex()==0){
            eCambia.setText("¿Cuál es su sueldo básico?");
        }
        else{
            eCambia.setText("¿Cuántos clientes tiene captado?");
        }
    }//GEN-LAST:event_comboEmpleadoActionPerformed

    private void lNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNombreActionPerformed

    private void lApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lApellidosActionPerformed

    private void lCambiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lCambiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lCambiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboEmpleado;
    private javax.swing.JLabel eApellidos;
    private javax.swing.JLabel eCambia;
    private javax.swing.JLabel eEmpleado;
    private javax.swing.JLabel eNombre;
    private javax.swing.JTextField lApellidos;
    private javax.swing.JTextField lCambia;
    private javax.swing.JTextField lNombre;
    // End of variables declaration//GEN-END:variables
}
