DROP FUNCTION t() CASCADE;
CREATE FUNCTION t()
	RETURNS TRIGGER
	LANGUAGE PLPGSQL
    AS 
$$  
DECLARE

BEGIN

  return new;
END;
$$;
CREATE TRIGGER tt before INSERT ON tabla for each row EXECUTE PROCEDURE t();
