services:
  # container apache
  apache:
    image: httpd:2.4
    ports:
      - "8000:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
    container_name: dam_web1

  apache2:
    image: httpd:2.4
    ports:
      - "9080:80"
    volumes:
      - ./htdocs:/usr/local/apache2/htdocs
    container_name: dam_web2