/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz;

import java.sql.Connection;
import javax.swing.JPanel;
import postgressql.ConexionSQL;

/**
 *
 * @author dam1
 */
public class CrearLibros extends javax.swing.JPanel {
    JPanel pMenu;
    ConexionSQL obxC = new ConexionSQL();
    String texto;
    
    /**
     * Creates new form CrearLibros
     */
    public CrearLibros() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lID = new javax.swing.JTextField();
        bCrear = new javax.swing.JButton();
        eID = new javax.swing.JLabel();
        eTitulo = new javax.swing.JLabel();
        lTitulo = new javax.swing.JTextField();
        eDescripcion = new javax.swing.JLabel();
        bVolver = new javax.swing.JButton();

        lID.setToolTipText("");
        lID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lIDActionPerformed(evt);
            }
        });

        bCrear.setText("CREAR");
        bCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearActionPerformed(evt);
            }
        });

        eID.setText("ID");

        eTitulo.setText("Titulo");

        lTitulo.setToolTipText("");
        lTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lTituloActionPerformed(evt);
            }
        });

        eDescripcion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        bVolver.setText("VOLVER");
        bVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(eDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(eID)
                            .addComponent(eTitulo))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(bVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eID))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eTitulo))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCrear)
                    .addComponent(bVolver))
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lIDActionPerformed

    private void bCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearActionPerformed
        if(!lTitulo.getText().equals("") && !lID.getText().equals("")){
            texto = obxC.insertarLibros(Integer.parseInt(lID.getText()),lTitulo.getText());
            eDescripcion.setText(texto);
            lTitulo.setText("");
            lID.setText("");
        }
        else{
            if(lTitulo.getText().equals("")){
                eDescripcion.setText("EL TITULO NO PUEDE SER VACIO");
            }
            else{
                eDescripcion.setText("EL ID NO PUEDE SER VACIO");
            }
        }
    }//GEN-LAST:event_bCrearActionPerformed

    private void lTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lTituloActionPerformed

    private void bVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVolverActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        pMenu.setVisible(true);
    }//GEN-LAST:event_bVolverActionPerformed

    public void recoger(JPanel panel){
        pMenu = panel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCrear;
    private javax.swing.JButton bVolver;
    private javax.swing.JLabel eDescripcion;
    private javax.swing.JLabel eID;
    private javax.swing.JLabel eTitulo;
    private javax.swing.JTextField lID;
    private javax.swing.JTextField lTitulo;
    // End of variables declaration//GEN-END:variables
}
