/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bonoloto;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dam1
 */
public class Ventana extends javax.swing.JFrame {
    ArrayList<Integer> listaElegida = new ArrayList();
    ArrayList<Integer> listaRandom = new ArrayList();
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tValores = new javax.swing.JTable();
        lEscoger = new javax.swing.JTextField();
        eNumeros = new javax.swing.JLabel();
        eAciertos = new javax.swing.JLabel();
        nAciertos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tValores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nº1", "nº2", "nº3", "nº4", "nº5", "nº6", "extra"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tValores);

        lEscoger.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lEscoger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lEscogerActionPerformed(evt);
            }
        });
        lEscoger.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lEscogerKeyPressed(evt);
            }
        });

        eNumeros.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        eNumeros.setText("ESCRIBA SUS NUMEROS");

        eAciertos.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        eAciertos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eAciertos.setText("ACIERTOS");

        nAciertos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel1.setText("Tu eleccion");

        jLabel2.setText("Eleccion ganadora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eNumeros)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(eAciertos)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lEscoger, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(eNumeros, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lEscoger, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addComponent(eAciertos)
                .addGap(31, 31, 31)
                .addComponent(nAciertos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lEscogerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lEscogerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lEscogerActionPerformed

    private void lEscogerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lEscogerKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            if(listaElegida.size() < 6){
                if(Integer.parseInt(lEscoger.getText())<51 && Integer.parseInt(lEscoger.getText())>0){
                    listaElegida.add(Integer.parseInt(lEscoger.getText()));
                    lEscoger.setText("");
                }
            }
            if(listaElegida.size()==6){
                aciertos();
            }
        }
        
    }//GEN-LAST:event_lEscogerKeyPressed
 
    
    private void aciertos(){
        int numero;
        eNumeros.setText("");
        lEscoger.enableInputMethods(false);
        
        //primera fila
        Integer[] fila = new Integer[7];
        for(int i = 0; i<listaElegida.size();i++){
            fila[i] = listaElegida.get(i);
        }
        DefaultTableModel model = (DefaultTableModel) tValores.getModel();
        model.addRow(fila);
        
        //segunda fila
        Integer[] fila2 = new Integer[7];
        
        numero = (int) (Math.random()*(51-1)+1);
        listaRandom.add(numero);
        fila2[0] = numero;
        
        for(int j=1; j < fila2.length; j++){
            numero = (int) (Math.random()*(51-1)+1);
            for(int i = 0; i < listaRandom.size(); i++){
                if(numero == fila2[i]){
                    numero = (int) (Math.random()*(51-1)+1);
                    i=0;
                }
            }
            fila2[j]=numero;
            listaRandom.add(numero);
        }
        model.addRow(fila2);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eAciertos;
    private javax.swing.JLabel eNumeros;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lEscoger;
    private javax.swing.JLabel nAciertos;
    private javax.swing.JTable tValores;
    // End of variables declaration//GEN-END:variables
}
