# Contenedor apache con php
version: '3.1'
services:
  web:
    image: php:7.2-apache
    container_name: apachePHP
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD = root
      - MYSQL_DATABASE = db
      - MYSQL_USER = user
      - MYSQL_PASSWORD = user